### PR TITLE
Added transitions to Optional fields add/remove

### PR DESCRIPTION
**Pull request by pricea1**
### What is the context of this PR?
Optional fields were not transitioning in/out

### How to review 
Toggling an "optional field" on a question page should result in that field transitioning in or out.

1. Create a questionnaire
2. Navigate to question page
3. Toggle an "optional field"
4. Pay attention to that field appearing or disappearing - master branch won't have the 200ms transition (opacity & size)

closes https://github.com/ONSdigital/eq-author-app/issues/273

### CODE REVIEW

**Comment by pricea1** [comment]
[eq-author-app: #273 - Optional fields should have transitions (Issue)](https://trello.com/c/YifYBqDD/1209-eq-author-app-273-optional-fields-should-have-transitions-issue)

**Comment by tgandrews** [comment]
@pricea1 how does the change here fix the issue?

**Comment by pricea1** [comment]
> @pricea1 how does the change here fix the issue?

AnswerTransition, a styled(CSSTransition), passes a className prop to the child which specifies the transition states e.g. answer-enter . 

The <MultipleFieldEditor /> child is a fragment so doesn't have a root element to attach the className.
The <RichTextEditor /> takes the className prop and applies it to an inner <Input /> element rather than the root.

**Comment by tgandrews** [comment]
Could we update the components instead to take the className prop?

**Comment by hamishtaplin** [comment]
> Could we update the components instead to take the className prop?

I prefer this too as it's not clear to the un-initiated what the `div` is for.

**Comment by pricea1** [comment]
> > Could we update the components instead to take the className prop?
> 
> I prefer this too as it's not clear to the un-initiated what the `div` is for.

Just updated my previous comment as tag didn't display properly.

I'll have a look. Not a problem for \<MultipleFieldEditor /> but  \<RichTextEditor /> intentionally passes the className prop down to its \<Input /> child. Not sure of the implications of this and whether className prop would get overwritten. I'll investigate. I can't see any instances where RichTextEditor is using the className prop.

Another approach would be for \<AnswerTransition /> to wrap everything in a \<div />. Would need testing for unintended issues.

**Comment by hamishtaplin** [comment]
> > > Could we update the components instead to take the className prop?
> > 
> > 
> > I prefer this too as it's not clear to the un-initiated what the `div` is for.
> 
> Just updated my previous comment as tag didn't display properly.
> 
> I'll have a look. Not a problem for <MultipleFieldEditor /> but <RichTextEditor /> intentionally passes the className prop down to its <Input /> child. Not sure of the implications of this and whether className prop would get overwritten. I'll investigate. I can't see any instances where RichTextEditor is using the className prop.
> 
> Another approach would be for <AnswerTransition /> to wrap everything in a <div />. Would need testing for unintended issues.

Sounds like it'll just get complicated. 

Keep the `div` but maybe add a comment to it explaining why it's there?

**Comment by pricea1** [comment]
Given that the extra div is a requirement of \<AnswerTransition />, I've refactored so a div is wrapped around the \<AnswerTransition/> children instead. It's a neater solution and means we don't have to think about it in future. Other AnswerTransitions still seem to work as intended.

**Pull request merged**
