### PR TITLE
Changed ErrorBoundary to use getDerivedStateFromError

### LINKED ISSUE #300: Change ErrorBoundary component to use recommended getDerivedStateFromError method
React has changed the way Error Boundaries work.

Recommended use is to use getDerivedStateFromError method instead of componentDidCatch. We currently setState within componentDidCatch. Both methods currently work but setting state within componentDidCatch will be deprecated in future:
[https://reactjs.org/docs/react-component.html#componentdidcatch](https://reactjs.org/docs/react-component.html#componentdidcatch)

The issue is with Enzyme simulateError() method, which currently only supports componentDidCatch. 
getDerivedStateFromError support was added to Enzyme on 13/03/19 but doesn't appear to be released yet:
[https://github.com/airbnb/enzyme/commit/e76ea4faf8fd05cf68c7180916bb43c51940b4e3#diff-dadb465087c92e620468f84ff841c848](https://github.com/airbnb/enzyme/commit/e76ea4faf8fd05cf68c7180916bb43c51940b4e3#diff-dadb465087c92e620468f84ff841c848)

### PR DESCRIPTION
**Pull request by pricea1**
### What is the context of this PR?
Change to use recommended getDerivedStateFromError method in errorBoundary now that Enzyme has been updated to support it.

### How to review 
1. Navigating to non-existent questionnaire redirects to page not found page.
2. Ensure tests pass

Closes #300

### CODE REVIEW

**Comment by pricea1** [comment]
https://github.com/ONSdigital/eq-author-app/issues/300

**Comment by pricea1** [comment]
[eq-author-app: #300 - Change ErrorBoundary component to use recommended getDerivedStateFromError method (Issue)](https://trello.com/c/B4gyeQjT/1208-eq-author-app-300-change-errorboundary-component-to-use-recommended-getderivedstatefromerror-method-issue)

**Comment by tgandrews** [comment]
@pricea1 did we already do the enzyme upgrade?

**Comment by pricea1** [comment]
> @pricea1 did we already do the enzyme upgrade?

@tgandrews yes. enzyme-adapter-react-16 is currently 1.14.0. Fix was applied in 1.6.0

**Pull request merged**
