### PR TITLE
EAR-1427-FEATURE-new-signin-page-create-account-journey

### PR DESCRIPTION
**Pull request by zimboflyman**
### What is the context of this PR?
https://collaborate2.ons.gov.uk/jira/browse/EAR-1427

This is the new user journey for creating an account, signing in and updating forgotten passwords
you will need|:
1. a usable email address to create a new account and test password reseting etc.
2. access to your local firebase console for your local author project - 

### How to review

1. Update your local firebase email template settings (See "how to" notes 1 below)
2. Follow the use journey from the prototype - https://overflow.io/s/X4759T1F?node=9f9fd844&prototype
3. you can easily delete new accounts in the Firebase console, so that you are able to use the same email address to test with etc.
4. any questions - just ask!😁

### Notes

1 - **environments**
In order to work on different environments
Template settings within each different firebase environment will need updating
within the relevant firebase console - 

- goto "Authentication"
- click on template tab
- edit template
- at the bottom of the page - customise action URL
- type in your url as per this example - http://localhost:3000/#/sign-in/ - replacing localhost:3000 with the correct url of your project.

**2 - Passwords**
Currently, Firebase only asks for a minimum of 6 characters with no other rules
We will need to add client side validation as minimum - and discuss options for server side validation for password
will need a separate ticket

### CODE REVIEW

**Review by farres1 — COMMENTED** [review]
I've sent Shane messages with any changes I've found while reviewing the sign in page. I've added multiple comments listing these in the PR.

**Review by farres1 — COMMENTED** [review]
MeContext, SignInPage test,  Header test, Input test and PrivateRoute all have unused code comments

**Review by farres1 — CHANGES_REQUESTED** [review]
The enter key cannot be used to sign in to Author

**Review by farres1 — COMMENTED** [review]
InlineDescription uses a margin-right of 0.5rem, which is displayed as two spaces instead of one (resolved)

**Review by farres1 — COMMENTED** [review]
Input/PasswordInput/Index.test.js

Rename to Input/PasswordInput/index.test.js with lower case index
DONE

**Comment by zimboflyman** [comment]
> The enter key cannot be used to sign in to Author

Tab to focus on the button - then enter - works

**Review by jasehumphr — CHANGES_REQUESTED** [review]
Main font for the login page needs to be font-family: OpenSans,Helvetica Neue,arial,sans-serif; instead of Lato. This is what is used on the GDS this is based on https://ons-design-system.netlify.app/components/header/#internal

**Comment by jasehumphr** [comment]
Few things on the look and feel
GDS stuff. The 1. Enter Password links to an anchor on the Enter password validation message.
https://ons-design-system.netlify.app/components/panel/examples/error-header/
Screenshot 2022-02-18 at 17 06 45

Also the padding between the lower password validation and the email input needs to be doubled

**Review by farres1 — DISMISSED** [review]

**Review by jasehumphr — APPROVED** [review]
Nice one Shane

**Review by farres1 — APPROVED** [review]

**Review by jasehumphr — APPROVED** [review]

**Review by jasehumphr — APPROVED** [review]
Happy Days

**Review by farres1 — APPROVED** [review]

**Pull request merged**
