### PR TITLE
Add response headers to improve security

### PR DESCRIPTION
**Pull request by adammahmood**
### What is the context of this PR?
- Adds [Helmet](https://www.npmjs.com/package/helmet) package which adds security response headers.  This is recommended by [ExpressJS](https://expressjs.com/en/advanced/best-practice-security.html) as best practice.
- Some headers have been modified as per recommendations in https://trello.com/c/bIUdMXZ6/810-ensure-that-secure-headers-are-all-set

### How to review 
- Ensure tests pass
- Ensure headers listed in https://trello.com/c/bIUdMXZ6/810-ensure-that-secure-headers-are-all-set can be seen in response headers for all network requests.

### CODE REVIEW

**Comment by adammahmood** [comment]
[Ensure that secure headers are all set](https://trello.com/c/bIUdMXZ6/810-ensure-that-secure-headers-are-all-set)

**Comment by jonnyshaw89** [comment]
@adammahmood do we want to add any tests to check the headers?

**Comment by adammahmood** [comment]
> @adammahmood do we want to add any tests to check the headers?

@jonnyshaw89 I've added a e2e cypress test to check the correct headers are set.  It's quite difficult to unit test and makes much more sense as an e2e test.  What do you think?

**Comment by jonnyshaw89** [comment]
@adammahmood yeh test looks ok. i just need to test it still loads in 3rd party JS

**Comment by jonnyshaw89** [comment]
@adammahmood Does it make sense to add any of this to Author and Publisher as well?

**Comment by adammahmood** [comment]
@jonnyshaw89 Yes. Definitely, worth adding to publisher as well.

**Comment by adammahmood** [comment]
I've added the headers to `eq-publisher`.  Ideally, it would have been great to have a config in the root but this isn't possible as you can't `require` a module outside of a projects scope.  An alternative solution would be to have a separate package which could be re-used - this seems overkill considering we are about to merge API / Publisher.

**Pull request merged**
