### PR TITLE
Drag and drop with one section

### PR DESCRIPTION
**Pull request by MattElcock**
### What is the context of this PR?

This is a prototype, created by EAR-1344, aimed to demonstrate how a drag and drop menu might look in Author. It was created using the React Beautiful DND library.

The prototype was built using the same components that comprise the existing navigaion bar.

### How to review

Have a look at Storybook and have a play around.

To use the keyboard support:

Tab through the page to focus on the right arrow symbol beside the section title
Press enter right arrow key - the collapsible will open
Carry on tabbing through and focus on a page
Press the space bar - this will select a page to grab
Using the arrow keys, move the page up and down
Press the space bar again - this will drop the page into the new position

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

### CODE REVIEW

**Comment by tbaggaley** [comment]
Hey Matt, tried this out in storybook and it's very cool. Looks like the library you chose will be super helpful. Hopefully the final bell will soon be tolling for the move modal!

Is the purpose of this PR so we have something in Storybook as a demo or are we hoping to expand on this particular component when we merge into the nav bar? In the latter case we could use some unit tests for it - otherwise happy to approve if it's just something to look at for now

**Comment by MattElcock** [comment]
> Hey Matt, tried this out in storybook and it's very cool. Looks like the library you chose will be super helpful. Hopefully the final bell will soon be tolling for the move modal!
> 
> Is the purpose of this PR so we have something in Storybook as a demo or are we hoping to expand on this particular component when we merge into the nav bar? In the latter case we could use some unit tests for it - otherwise happy to approve if it's just something to look at for now

Cheers mate!

Yeah, at this stage it's just a demo to inform Joes designs. No need for unit tetsts at this point.

**Review by tbaggaley — APPROVED** [review]
Superfantastico

**Review by zimboflyman — APPROVED** [review]
nice looking library

**Pull request merged**
