### PR TITLE
Ear 1229 nested validation dont work with pubsub disabled

### PR DESCRIPTION
**Pull request by ashtuck**
### Context of PR ###

When PubSub is disabled. Error messages weren't updating due to not enough data being passed down in the GraphQL calls.

### How to review ###

- Go to `eq-author-api/schema/resolvers/createMutation.js`.
- Comment out lines `51-55`. This disables PubSub.
- Create a question with a Routing Rule.
- Check that the error messages disappear and update correctly.
- Create a some Skip Logic and check that the error messages disappear and update correctly.
- UnComment lines `51-55` in `createMutation.js` to reenable PubSub.

What to do after everything is green
    *   Bring this branch up-to-date with Origin/Master
    *   If there are a lot of commits or some are not helpful to read, squash them down
    *   Click the Merge button on this pull request
    *   Does this change mean the Capability examples questionnaire should be updated?
    *   Move the Jira ticket for this task into the next stage of the process

### CODE REVIEW

**Review by jasehumphr — APPROVED** [review]

**Review by farres1 — CHANGES_REQUESTED** [review]
This looks really good!

If you click the plus button on a routing rule or skip rule, the error badge doesn't update for the new errors until the page is refreshed

**Review by martyncolmer — APPROVED** [review]

**Review by farres1 — CHANGES_REQUESTED** [review]
The previous error is fixed for me once an operator is selected, but before that the errors are still displayed. This means if you select an operator before selecting AND / OR, either refresh is required to remove the error or the operator must be reselected.

**Comment by ashtuck** [comment]
> The previous error is fixed for me once an operator is selected, but before that the errors are still displayed. This means if you select an operator before selecting AND / OR, either refresh is required to remove the error or the operator must be reselected.

This has been fixed. There might be some other edge cases, if any others come up. I've gone through and i think that should be all of it i now. But let me know.

**Review by farres1 — CHANGES_REQUESTED** [review]
The error stays when an answer is selected from "Select an answer" on an AND / OR logic condition

**Review by farres1 — APPROVED** [review]

**Review by MattElcock — APPROVED** [review]

**Pull request merged**
