### PR TITLE
JSON DB - Cypress failures

### PR DESCRIPTION
**Pull request by tgandrews**
### What is the context of this PR?
~Fix cypress failures apart from:~
1. ~Routing ~(still in active dev #171)~ Now in progress~
2. ~e2e as publisher isn't working yet. But works when rebased on #178~

No local cypress failures

### How to review 
1. That all cypress tests ~(apart from routing and e2e)~ pass successfully

### CODE REVIEW

**Comment by tgandrews** [comment]
I’ll have a look at them as it was passing locally before the rebase

**Comment by tgandrews** [comment]
@samiwel Header seems to be passing for me do you have any more details? I can definitely see the issue with validation; after the rebase the min value validation against previous answer came in so I need to get that working.

**Comment by jonnyshaw89** [comment]
How are we going to ensure that these tests keep passing? as the CI builds don't currently get this far.

**Comment by tgandrews** [comment]
Maybe I make a change to travis to run these first? Just for the moment?

**Comment by jonnyshaw89** [comment]
@tgandrews Could we make travis not fail instantly on test failures? but fail after everything runs?

**Comment by tgandrews** [comment]
@jonnyshaw89 I can't see anything obvious. But this is a definite concern. Maybe we just work on getting the tests passing on author and api. 

I'm working on the author failures at the moment and I think @samiwel is looking at the API.

**Comment by samiwel** [comment]
[Fix JSON DB Cypress tests](https://trello.com/c/HAUf0J5L/864-fix-json-db-cypress-tests)

**Comment by samiwel** [comment]
Retested this locally. Initially I had the same failures as before when running all tests, but upon running the failing tests in isolation they worked correctly. Happy to approve this PR for now as it's a big step in the right direction even if there is some worked required later to improve flakiness of the test.

Getting these tests running on travis would be a good indication.

**Pull request merged**
