### PR TITLE
GitHub actions update

### PR DESCRIPTION
**Pull request by MattElcock**
### What is the context of this PR?

GitHub Actions always fails on dependency PRs. This is because Docker uses the branch name from dependabot to build and tag it's images, but the format is incorrect. Irregardless, we do not need to make new Docker images and push them for dependency PRs as when we merge them into master, an image with all the updated dependencies is made anyway.

Additionally, on all PRs, an image is made regardless of if the code actually works.

This PR makes sure that the tests have passed before a Docker image is made. If the PR is a dependency PR (known by the 'dependency' label being present, which is automatically added on Dependabot PRs), it does not run the build scrips for the Docker images.

### How to review 

Ensure all the tests are passing and nothing looks weird.

* Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
    * ensure it can be opened in Author;
    * then, ensure it can be viewed in Runner by pressing the **view survey** button
* Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. * [ ] Bring this branch up-to-date with Origin/Master
2. * [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. * [ ] Click the **Merge** button on this pull request
4. * [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. * [ ] Move the Jira ticket for this task into the next stage of the process

### CODE REVIEW

**Review by zimboflyman — APPROVED** [review]

**Comment by tjamesmac** [comment]
@MattElcock previously if the unit tests failed did the build carry on or end the process there?

Nice that they've separated out into build and test because at a quick glance we can see if it's docker related or not.

**Review by tjamesmac — APPROVED** [review]
Marvellous

**Comment by MattElcock** [comment]
> @MattElcock previously if the unit tests failed did the build carry on or end the process there?
> 
> Nice that they've separated out into build and test because at a quick glance we can see if it's docker related or not.

Derp. Unit tests would fail. Ignore my point in the PR around pushing broken code.

**Comment by tjamesmac** [comment]
Oh no that's okay, I wasn't even thinking about that!

**Pull request merged**
