### PR TITLE
EAR 1462 Add validation error to date modal

### PR DESCRIPTION
**Pull request by farres1**
> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

Add validation error message to the date modal when a custom date or metadata date has not been entered

### How to review

**Check:**
- [x] Modal shows an error message when before/after custom date has not been entered (date range and date answers)
- [x] Modal shows an error message when before/after metadata date has not been entered (date range and date answers)

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

### CODE REVIEW

**Review by ashtuck — DISMISSED** [review]

**Review by zimboflyman — APPROVED** [review]
works good!

**Review by martyncolmer — CHANGES_REQUESTED** [review]
Need highlighting round input box

**Review by ashtuck — DISMISSED** [review]

**Review by jasehumphr — APPROVED** [review]

**Review by martyncolmer — APPROVED** [review]

**Review by jasehumphr — APPROVED** [review]
Bingo

**Review by martyncolmer — DISMISSED** [review]

**Review by jasehumphr — APPROVED** [review]

**Review by MattElcock — CHANGES_REQUESTED** [review]
Nice work Sam. 

You have fixed the existing tests but haven't written any new ones. Could you add some tests to assert that the error message shows under the particular conditions, please?

**Review by ashtuck — APPROVED** [review]

**Review by jasehumphr — APPROVED** [review]

**Pull request merged**
